version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - test
          filters:
            branches:
              only: master
jobs:
  test:
    docker:
      - image: circleci/node:12
    working_directory: ~/hacker-news-clone
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm test
